name: Release Mobile File
on:
    [ workflow_dispatch,
     push:
        tags:
            - v*]

jobs:
    Publish:
        if: github.repository == 'VendroidEnhanced/Vencord'
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: check that tag matches package.json version
              run: |
                  pkg_version="v$(jq -r .version < package.json)"
                  if [[ "${{ github.ref_name }}" != "$pkg_version" ]]; then
                      echo "Tag ${{ github.ref_name }} does not match package.json version $pkg_version" >&2
                      exit 1
                  fi

            - uses: pnpm/action-setup@v2 # Install pnpm using packageManager key in package.json

            - name: Use Node.js 19
              uses: actions/setup-node@v3
              with:
                  node-version: 19
                  cache: "pnpm"

            - name: ls
              run: ls
