name: Release Mobile File
on: workflow_dispatch

jobs:
    Publish:
        if: github.repository == 'VendroidEnhanced/Vencord'
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2 # Install pnpm using packageManager key in package.json

            - name: Use Node.js 19
              uses: actions/setup-node@v3
              with:
                  node-version: 19
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile
              
            - name: Bomb arrpc
              run: rm -r src/plugins/arRPC.web

            - name: Build web
              run: pnpm buildWeb --standalone

            - name: Make a release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: release
                release_name: release
                draft: false
                prerelease: false
        
            - uses: actions/upload-release-asset@v1.0.1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./dist/browser.js
                asset_name: mobile.js
                asset_content_type: text/javascript
        
            - uses: eregon/publish-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                release_id: ${{ steps.create_release.outputs.id }}

            
